Add handling of self webworker context
pine/arraybuffer-loader pull request #48
Opened 2021-12-13 08:42 UTC by wclr

Fixes #47

2023-02-12 11:30 UTC, M00TSDNS requested changes
as I understand it, single quotes please!

2023-02-12 11:30 UTC, M00TSDNS commented on lib/arraybuffer-loader.js
> +  const request = require.resolve("./to-array-buffer.js");
This repository appears to use single quotes only @wclr

2023-02-16 06:04 UTC, pine commented on lib/arraybuffer-loader.js
> +  const request = require.resolve("./to-array-buffer.js");
Hello @M00TSDNS.

Thank you for your review, and I'm sorry for waiting you.
I will check the Pull Request today.

2023-02-16 06:15 UTC, pine commented
Hello @wclr.
Thank you for your contribution. I'm sorry for waiting you long time.

I'm concerned about code style @M00TSDNS also said, but I will fix it after merging this.

2023-02-16 06:15 UTC, merged

2023-02-16 06:45 UTC, M00TSDNS commented
It's no worries Pine, hope life is treating you well!